"""Remove username field from users table

Revision ID: 28866536becb
Revises: b1e7ccb1cf7e
Create Date: 2025-10-26 14:58:40.057634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28866536becb'
down_revision = 'b1e7ccb1cf7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    # ### end Alembic commands ###
